"""Provider-neutral code intelligence for Claim Plane."""

from claim_plane.code_intelligence.base import (
    CODE_INTELLIGENCE_PROVIDER_PROTOCOL,
    CODE_INTELLIGENCE_SNAPSHOT_PROTOCOL,
    CodeIntelligenceCapability,
    CodeIntelligenceProvider,
    CodeIntelligenceProviderError,
    CodeIntelligenceProviderManifest,
    CodeIntelligenceRequest,
    CodeIntelligenceSnapshot,
    CodeIntelligenceUnsupportedRequest,
)
from claim_plane.code_intelligence.builtin import (
    BUILTIN_PYTHON_PROVIDER_ID,
    BUILTIN_PYTHON_PROVIDER_VERSION,
    BuiltinPythonCodeIntelligenceProvider,
)
from claim_plane.code_intelligence.scip import (
    DEFAULT_SCIP_ENVIRONMENT_PROBE_COMMAND,
    DEFAULT_SCIP_INDEX_TIMEOUT_SECONDS,
    DEFAULT_SCIP_PYTHON_COMMAND,
    SCIP_INDEX_ARTIFACT_PROTOCOL,
    SCIP_INDEX_CACHE_PROTOCOL,
    SCIP_INDEX_CACHE_SCHEMA,
    ScipIndexArtifact,
    ScipIndexError,
    ScipIndexerConfig,
    ScipIndexerFailed,
    ScipIndexerUnavailable,
    ScipIndexManager,
    ScipRevisionCache,
    ScipRepositoryState,
    ScipRevisionMismatch,
    capture_scip_repository_state,
)
from claim_plane.code_intelligence.registry import (
    CodeIntelligenceProviderRegistry,
    analyze_code_intelligence,
    default_code_intelligence_registry,
)

__all__ = [
    "BUILTIN_PYTHON_PROVIDER_ID",
    "DEFAULT_SCIP_ENVIRONMENT_PROBE_COMMAND",
    "DEFAULT_SCIP_INDEX_TIMEOUT_SECONDS",
    "DEFAULT_SCIP_PYTHON_COMMAND",
    "SCIP_INDEX_ARTIFACT_PROTOCOL",
    "SCIP_INDEX_CACHE_PROTOCOL",
    "SCIP_INDEX_CACHE_SCHEMA",
    "ScipIndexArtifact",
    "ScipIndexError",
    "ScipIndexerConfig",
    "ScipIndexerFailed",
    "ScipIndexerUnavailable",
    "ScipIndexManager",
    "ScipRevisionCache",
    "ScipRepositoryState",
    "ScipRevisionMismatch",
    "capture_scip_repository_state",
    "BUILTIN_PYTHON_PROVIDER_VERSION",
    "CODE_INTELLIGENCE_PROVIDER_PROTOCOL",
    "CODE_INTELLIGENCE_SNAPSHOT_PROTOCOL",
    "BuiltinPythonCodeIntelligenceProvider",
    "CodeIntelligenceCapability",
    "CodeIntelligenceProvider",
    "CodeIntelligenceProviderError",
    "CodeIntelligenceProviderManifest",
    "CodeIntelligenceProviderRegistry",
    "CodeIntelligenceRequest",
    "CodeIntelligenceSnapshot",
    "CodeIntelligenceUnsupportedRequest",
    "analyze_code_intelligence",
    "default_code_intelligence_registry",
]
